### ISSUE TITLE
Models not found on nested structure not at first level

### ISSUE THREAD

**Issue by sanchric-forvia** [ad-on-is/adonis-autoswagger#100]
On a project, models are at this kind of route 

> app/models/example/v1_0/model.ts

the get files function was runnig asyn on depper levels, causing race conditions and returning and empty result, my quick fix was add await on recursive get files

![image](https://github.com/ad-on-is/adonis-autoswagger/assets/168569160/5fe50f90-6b70-4d23-a150-54839edf71b3)

**Comment by ad-on-is** [comment]
Oh.. thx... I forgot to put an await in there.

Fixed in 3.50.0!
