### ISSUE TITLE
Wrong @responseBody object scheme generation 

### ISSUE THREAD

**Issue by GilTRipper** [ad-on-is/adonis-autoswagger#101]
```
  /*
   * @store
   * @requestBody - <createPostValidator>
   * @responseBody 200 - {"post": <Post>}
   */
  async store({ auth, request }: HttpContext) {
    const user = auth.getUserOrFail()
    const data = await request.validateUsing(createPostValidator)
    const post = await this.postService.create(data, user)

    return { post }
  }
```
  in this example we want response to be JSON object with post field that includes PostScheme
  but in the end we have this scheme
  
   ```
post:
      summary: " (store)"
      description: "\n\n _app/controllers/api/posts_controller.ts_ - **store**"
      parameters: []
      tags:
        - "POSTS"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"
              example:
                id: 742
                title: "Lorem Ipsum"
                description: "Lorem ipsum dolor sit amet"
                user_id: 978
                created_at: "2021-03-23T16:13:08.489+01:00"
                updated_at: "2021-03-23T16:13:08.489+01:00"
```

so it must be not just **Post** model response but JSON: {post: **Post**}

**Comment by ad-on-is** [comment]
you need to wrap <Post> with quotes "<Post>"

**Comment by GilTRipper** [comment]
```
 post:
      summary: " (store)"
      description: "\n\n _app/controllers/api/posts_controller.ts_ - **store**"
      parameters: []
      tags:
        - "POSTS"
      responses:
        200:
          content:
            application/json:
              schema:
                type: "object"
              example:
                post:
                  id: 669
                  title: "Lorem Ipsum"
                  description: "Lorem ipsum dolor sit amet"
                  user_id: 962
                  created_at: "2021-03-23T16:13:08.489+01:00"
                  updated_at: "2021-03-23T16:13:08.489+01:00"
```
when i wrap < Post > in double quotes its okay with example. But schema becomes any object

**Comment by GilTRipper** [comment]
Btw have one more issue with rendering docs. 
`return AutoSwagger.default.docs(router.toJSON(), swagger)`
the code above throws an error that validator/post.ts doesn't exist
but when running command
`node ace docs:generate`
everything is fine and all validators are passed to schema

**Comment by ad-on-is** [comment]
> ```
>  post:
>       summary: " (store)"
>       description: "\n\n _app/controllers/api/posts_controller.ts_ - **store**"
>       parameters: []
>       tags:
>         - "POSTS"
>       responses:
>         200:
>           content:
>             application/json:
>               schema:
>                 type: "object"
>               example:
>                 post:
>                   id: 669
>                   title: "Lorem Ipsum"
>                   description: "Lorem ipsum dolor sit amet"
>                   user_id: 962
>                   created_at: "2021-03-23T16:13:08.489+01:00"
>                   updated_at: "2021-03-23T16:13:08.489+01:00"
> ```
> 
> when i wrap < Post > in double quotes its okay with example. But schema becomes any object

That's normal, because I'd have to generate a new schema for each and every custom json that is provided. This is out of scope

**Comment by GilTRipper** [comment]
It's not normal. Because we generate client api based on this docs. And as a result we have no response type.

**Comment by ad-on-is** [comment]
> It's not normal. Because we generate client api based on this docs. And as a result we have no response type.

What I meant by normal is , you did not do anything wrong here. 😅

I didn't know this would blow up so much that people would use it to autogenerate other stuff based on this one.

If you need it, fell free to submit a PR.

**Comment by GilTRipper** [comment]
Got it
What about second question? 
or better to create new issue?

**Comment by ad-on-is** [comment]
Alternatively, you can create an Interface and use that instead of {"post": "< Post>"}

```ts

expost interface PostInterface {
post: Post
}

```

Yeah, please create a separate issue for the other one. with the error that it produces, and the validator you use.

**Comment by ad-on-is** [comment]
This is now fixed in the latest version... No need for custom interfaces anymore

**Comment by mahdigh99** [comment]
in adonis 5 its work like this:
`   * @responseBody 200 - {"post": "Record<Post>" }`
