### ISSUE TITLE
"json.properties is not iterable" error when generating

### ISSUE THREAD

**Issue by oanylund** [ad-on-is/adonis-autoswagger#103]
```
json.properties is not iterable
          at ValidatorParser.parseSchema (/.../node_modules/adonis-autoswagger/dist/parsers.js:705:29)
```

This seems to be introduced with the new validator feature. looking at the json object there is an `each` property that has a `properties` array. If i patch the code to use the `each` property, it generates successfully

Adonis core version:  6.12.0
Vine version: 2.1.0

**Comment by ad-on-is** [comment]
What exactly did you change and where? Also, under what circumstances does that happen? Could you provide more info?
