### ISSUE TITLE
Bug: Swagger returns empty object for controller with responseBody validator

### ISSUE THREAD

**Issue by IgorsKolcins** [ad-on-is/adonis-autoswagger#120]
## Description:

When using validator for reponseBody, it is not generating responseBody type when result object has only integer properties.

## How to reproduce:
1. Create controller `app/controllers/salons_controller.ts` (don't forget to define route to it):
```
import type { HttpContext } from '@adonisjs/core/http'
import { salonDeleteByUserIdResponse } from '#validators/salon'

export default class SalonsController {
  /**
   * @deleteByUserId
   * @responseBody 200 - <salonDeleteByUserIdResponse>
   */
  async deleteByUserId({ request }: HttpContext) {
    const salon = { id: 1 }

    return await salonDeleteByUserIdResponse.validate({
      salon: {
        id: salon.id,
      },
    })
  }
}
```
2. Create validator `app/validators/salon.ts`
```
import vine from '@vinejs/vine'

export const salonDeleteByUserIdResponse = vine.compile(
    vine.object({
        salon: vine.object({
            id: vine.number(),
        }),
    })
)
```
3. Start server and go to `/docs` page

## Expected result
Type is shown correctly
![image](https://github.com/user-attachments/assets/1c9ca1ab-fefe-40f6-a8b6-d06e7a688202)

## Actual result
Type is empty object
![image](https://github.com/user-attachments/assets/728f6b3e-9074-4ca1-a809-5ec1fd0f6ba4)

**Comment by IgorsKolcins** [comment]
I have added a fix for that issue in my fork, please check and approve PR: https://github.com/ad-on-is/adonis-autoswagger/pull/121

**Comment by ad-on-is** [comment]
Added in 3.63 - Thx @IgorsKolcins
