### ISSUE TITLE
definition of endpoints, protected by the auth-middlware does not work.

### ISSUE THREAD

**Issue by RimidalU** [ad-on-is/adonis-autoswagger#14]
I tried manually adding 'security: BearerAuth', but it didn't work, although I tried different spellings...

middleware connection:

> 
> ...
>     Route
>       .group(() => {
>         Route.delete('/delete/:id', 'ApartmentsController.delete')
>         Route.post('/create', 'ApartmentsController.create')
>         Route.post('/update', 'ApartmentsController.update')
>       })
>       .prefix('apartments')
>   })
>   .prefix('/api/v1').middleware('apiAuth')
> 
> 

adonis-autoswagger:

> ...
>     Route.get('/docs', async () => {
>       return AutoSwagger.ui('/swagger')
>     })
>   })
>   .prefix('/api/v1')
> 
> Route.get('/swagger', async () => {
>   return await AutoSwagger.docs(Route.toJSON(), {
>     path: __dirname,
>     title: 'Rento',
>     version: '1.0.0',
>     tagIndex: 3,
>     ignore: ['/swagger', '/docs', '/', '/health', '/uploads/*'],
>     common: {
>       parameters: {},
>       headers: {},
>     },
>     snakeCase: false
>   })
> })
>

**Comment by ad-on-is** [comment]
What exactly do you mean by "it didn't work". Does it throw errors, or does it just not recognize it as an auth-protected endpoint?

**Comment by RimidalU** [comment]
- I tried to slip something like 'BearerAuth' or 'bearer' using the example of the settings of the original swagger. What I think was pointless))
- it does not recognize it as an authorization-protected endpoint. Renders it correctly, but does not add a security property to every operation in the Swagger document, which is displayed in the UI as a padlock next to the operation.
![image](https://user-images.githubusercontent.com/81852394/165152198-d0348f23-e451-4040-bc56-19b6ed7f5ed7.png)

**Comment by ad-on-is** [comment]
Do you have a middleware called `auth` or `auth:api` applied to your routes?, this is where autoswagger automatically detects it. Custom middleware-names for auth are not supported yet.

**Comment by RimidalU** [comment]
Thanks a lot! Works! :relaxed:
