### ISSUE TITLE
Error on generate doc, trim

### ISSUE THREAD

**Issue by Shahere** [ad-on-is/adonis-autoswagger#140]
Hi ! thanks for the tool, I struggle to add autoswagger in my Adonis projet.

When i run the command : ```node ace docs:generate```
or if a access to the endpoint ```/docs```

I got : 

```
err: {
      "type": "TypeError",
      "message": "Cannot read properties of undefined (reading 'trim')"
}
```

Step to reproduce : follow the readme

Thanks for your help !

**Comment by rikad** [comment]
i got same error, my project is used adonis v5. i have some models with an undeclared type function.

so i solved with give that function with type example

```
public async getAbility(): Promise<any> {
   //
}
```

**Comment by Shahere** [comment]
Hi ! 
I finally manage to use swagger with Adonis with ```swaggerJsdoc```. swaggerJsdoc put all information in a JSON and i use a static html file to display it on a url.
You can use docker as well
