### ISSUE TITLE
Internal Server Error /swagger

### ISSUE THREAD

**Issue by Ortiix85** [ad-on-is/adonis-autoswagger#142]
Hello,

I tried to install AutoSwagger for my Adonis project, but when I run it, I get an internal server error on /swagger.

Here’s the response:

{
  "message": "ENOENT: no such file or directory, open 'C:\\Users\\......\\app\\AuthController.ts'", 
  "name": "Error",
  "status": 500,
  "frames": []
}

I followed the installation guide correctly. Note that I have a file named auth_controller.ts located in App/Controllers/. I'm wondering if it’s possible to specify where AutoSwagger should look for this file.

Thanks in advance for your help!

**Comment by erikmaday** [comment]
@Ortiix85 I see you closed this, what ended up being the fix?
