### ISSUE TITLE
DocGenerator wants to import ../config/swagger

### ISSUE THREAD

**Issue by rockymontana** [ad-on-is/adonis-autoswagger#15]
Hello.
I'm using this package and now I tried to deploy it to production.
I had missed that I had to do a li'l bit of extra stuff to get the docs to work properly in prod though.
So when I tried to follow the guide for production I see that the DocsGenerate.ts.example tries to import a ../config/swagger 
What should that file contain? I can't see an example of that it in this repo.

**Comment by ad-on-is** [comment]
Oh sorry... In my projects, I've moved the configuration to config/swagger.ts, and forgot to suggest the same in the docs.

**Comment by ad-on-is** [comment]
I've adapted the docs accordingly
