### ISSUE TITLE
Error when body contain primitive array

### ISSUE THREAD

**Issue by raf-eteg** [ad-on-is/adonis-autoswagger#16]
Ex:
* @requestBody { "ids": [2, 3, 7], "description": "xulambs" }

Produces:
{
  "ids": {
    "0": 2,
    "1": 3,
    "2": 7
  },
  "description": "xulambs"
}

To solve I did, in autoswagger.js:
jsonToRef(json) {
        let out = {};
        for (let [k, v] of Object.entries(json)) {
            if (typeof v === "object") {
//                v = this.jsonToRef(v);
                if (!Array.isArray(v) || !v.reduce((p, c) => p && c !== Object(c), true)) v = this.jsonToRef(v);

**Comment by ad-on-is** [comment]
Thank you very much.. I did a slight modification, now it applies to primitive and model arrays.
