### ISSUE TITLE
Why is the Patch Method ignored by the autogenerator?

### ISSUE THREAD

**Issue by 0p3r4t0r** [ad-on-is/adonis-autoswagger#19]
Here on [line 247] (with the most recent commit at the time of writing being [de43f67](https://github.com/ad-on-is/adonis-autoswagger/commit/de43f67a525496b3e41cede278f16c839af33146)) I noticed that you're ignoring routes with the PATCH method. Could you explain why you chose to do this?

In my particular case I have the following which is not picked up by swagger-autogen
```ts
  Route.patch('/:id', 'SomeController.update')
```

```ts
  /**
   * @update
   * @paramPath id - SomeId
   * @requestBody { "data": "some data" } // Expects model specification
   */
  public async update({ request, response, params }: HttpContextContract) {
      ...some update code
  }
```

If I add a line to the if statement at [line 247] and log the route it does come out, so it seems to me that it being ignored was intentional. Is there a reason for this?

[line 247]: https://github.com/0p3r4t0r/adonis-autoswagger/blob/de43f67a525496b3e41cede278f16c839af33146/src/autoswagger.ts#L247

**Comment by ad-on-is** [comment]
Oooh shoot...

In my case, adonisJS exposes **both** PUT and PATCH for update() methods, when using Route.resource() , resulting in duplicate entries, so I simply ignored one of them.

This needs a quick fix asap

**Comment by 0p3r4t0r** [comment]
@ad-on-is Good question, but no I only have patch. Here's what I get when I log the route...

```ts
{
  methods: [ 'PATCH' ],
  pattern: '/somethings/:id',
  handler: 'SomeController.update',
  meta: {
    namespace: undefined,
    resolvedHandler: {
    ...
```

It seems to me from [line 109] of [adonisjs/https-server](https://github.com/adonisjs/http-server) that we're stuck with PUT and PATCH when using `Route.resource`. Other Rails-style frameworks (I'm thinking of Laravel specifically) also use PUT and PATCH both for resource routes, so I don't think it's likely that we could disable one of the other in Adonis.

What about being able to use `@PATCH` `@PUT` on the update method to decide on one or the other method. Inspired by [Swagger 2.x Operations](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations#operation-annotations)

Let me know what you think, and if we can decide on a good solution I'm willing to give the PR a try.

[line 109]: https://github.com/adonisjs/http-server/blob/6cc8708efcd4b53b0cbc0a965660f9d2f4d16f98/src/Router/Resource.ts#L109

**Comment by ad-on-is** [comment]
`methods: [ 'PATCH' ]` but my logic (assuming it's working correctly) should only fire in this case `methods: [ 'PATCH', 'PUT' ]`
I'll take a look into it.

> What about being able to use @PATCH @PUT
I don't think there's a need for that, since it's already there, automatically. There's also no need to let users decide which one to use, since the API works for both, it's just about what's shown in the docs.

**Comment by ad-on-is** [comment]
I've fixed it in 1.8.0

**Comment by ad-on-is** [comment]
The problem is, that swagger has no option to display the two verbs for one route, instead it creates two, which is redundant. At the end, the doc is for someone consuming the API, and imho, for them it doesn't matter whether they use PUT or PATCH, since both are valid... the docs are just here to say... "yo... use PUT don't use POST or GET".

**Comment by 0p3r4t0r** [comment]
> The problem is, that swagger has no option to display the two verbs for one route, instead it creates two, which is redundant.

It may be redundant if you're API is not RESTful and you allow a request to PUT containing a partial object to only update some fields. Whether or not it's actually redundant is an implementation detail. If it's redundant then fine, we can turn it off with configuration.

> the docs are just here to say... "yo... use PUT don't use POST or GET". And if they try to use PATCH
> and still get a valid response, well, so be it.

So adonis-autoswagger is trying to say "yo... use PUT for update don't use PATCH"? Again, I think this is a decision that the designer of the API should make, and the docs should be able to reflect whichever method they chose, or both.

Imagine an endpoint like this

```ts
  public async update({ request, response, params }: HttpContextContract) {
    const something = await Something.findOrFail(params.id)
    
    if (request.method === 'PUT') {
      // validate that the payload contains a full object or throw error
      // upsert the object
    } else {
       // Overwrite the fields in the payload
    }
  }
```

I think I understand your opinion: you're right you could totally implement an API using PUT over PATCH, but there's no reason you have to, and the docs shouldn't be constrained to that use-case. I think the docs should reflect the way the API was intended to be used, and since PATCH is a valid intention we should be able to reflect that in the docs.

Sorry this is a little long-winded. Thanks so much for your time and explanations.

**Comment by ad-on-is** [comment]
Actually, these are valid points... I never thought someone would use `if(request.method === 'PUT') ... else ... `

**Comment by ad-on-is** [comment]
1.8.1 has now a setting to specify which to use, defaults to PUT... Regarding the other one, where both may be applied to the same controller action, I need to think that through (do a bit research), since maybe having `if(request.method === 'PUT') ... else ...` might even be a bad api-design.

`PUT /example` requires to specify `@requestBody` and `@responseBody` ... 

`PUT & PATCh /example` would require something like `@putRequestBody, @patchRequestBody, @putResponseBody, @patchResponseBody`

**Comment by 0p3r4t0r** [comment]
Since Adonis is a rails-style framework I thought it appropriate to examine the motivation behind why PATCH and PUT are both supported in `update` in the first place. I believe I found the reason in [issue 348 from Rails](https://github.com/rails/rails/issues/348).

From what I gather PUT should have been changed to PATCH (to be RESTful), then PATCH was added with PUT being left for backward compatibility.

I think you're right: you shouldn't actually support both and this plugin seems to be in the best spot regarding this issue after the updates from 1.8.1.

**Comment by ad-on-is** [comment]
https://stackoverflow.com/questions/28459418/use-of-put-vs-patch-methods-in-rest-api-real-life-scenarios

As you said, if someone wants to use PUT to update the object, PATCH only one field... this could be solved with 2 actions and is maybe even cleaner

```js
Route.resource('users', 'UsersController').apiOnly() // GET,POST,PUT,DELETE .. will handle create(),udpate(),show(),destroy()
Route.patch('users', 'UsersController.patch') // PATCH ... will handle patch()

```
