### ISSUE TITLE
README: examples of @param Type comment and Schema spec

### ISSUE THREAD

**Issue by senaki** [ad-on-is/adonis-autoswagger#20]
Hello, I'd like to use comment to describe my swagger. I get stucked on @param markup that lacks an example.
In my case, the resulting swagger.yml all @param Query as required and of type string for example. I'd like to alter this so that "* required" annotation disappears and type be integer on some params.

**Comment by ad-on-is** [comment]
there is no `@param` only `@paramPath` and `@paramQuery` as of now.

example for `/api/users/:id`

```js
// @paramPath id - The users id - @example(10)
public async show(ctx) {}
```

**Comment by senaki** [comment]
> there is no `@param` only `@paramPath` and `@paramQuery` as of now.
> 
> example for `/api/users/:id`
> 
> ```js
> // @paramPath id - The users id - @example(10)
> public async show(ctx) {}
> ```

thanx.

I have the same question with Models.
I have created in Model folder a model like
```
export default class Model{
 prop_a: type;
 prop_b: type;
}
```
then in my comment block 
```
/**
* \@responseBody 200 - <Model>
* /
```
The expected behavior is the model to be "seririalized" in web ui, no ? 
I obtain : 
`Returns a single instance of type Model without any relations. Take a look at the example for further details.`
The example is an empty JSON.
Giving the example JSON does not produce the expected output

**Comment by ad-on-is** [comment]
your props are not public, therefore they are not returned.

public prop_a: type

should work

**Comment by senaki** [comment]
It works by adding public members, Thanx again ! 
However, in the web ui, there is something queer.
Here is my model to be factual 
```
class Pagination {
    //@example(1)
    public page:number;
    //@example(5)
    public total:number;
    //@example(10)
    public perPage:number;
};

class Result {
    //@example(123456789)
    public dateEpoch: number;
};

//@description my model
class model {
    //@description array of result for each
    public records:Result[];
    //@example({page:1, total:5, perPage:10})
    public pages:Pagination;
}
export default new searchResponse;
``` 

then, in my controller, I have my callback function
```
//@description a description
//@responseBody 200 - <SearchResponse>
public async search( ...)
```
I expect in example  a schema looking like : 
```
{
 "records": [ { "dateEpoch": XX}, ],
"pages": { "page": X, "total": Y, "perPage": Z}
}
```
but I obtain
```
{
 "page": X, 
"total": Y, 
"perPage": Z,
 "dateEpoch": XX,
 "records": ...,
"pages": {}
}
```
I don't see why

**Comment by senaki** [comment]
> why isn't your model extending basemodel?

I defined it like that. Is it necessary ? Maybe my model is not optimal.  If so, should it look like 
```
import {BaseMode} from '@ioc:Adonis/Lucid/Orm';
class model extends BaseModel ...
...
?

**Comment by senaki** [comment]
thx for your help. 
I am  begginning with this framework and there are subtlties I don't master yet.
thx again !
