### ISSUE TITLE
No request found?

### ISSUE THREAD

**Issue by deri387** [ad-on-is/adonis-autoswagger#22]
I can't see request parameter on swagger, am i wrong setup?pls tell me how to show?
<img width="1389" alt="Screen Shot 2022-11-18 at 16 54 08" src="https://user-images.githubusercontent.com/37043134/202673778-21863f37-316c-4f08-bbb1-336b7fa1fcf7.png">

**Comment by ad-on-is** [comment]
Params are provided via comments in the controller... did you consult the README?
