### ISSUE TITLE
It's just a typo :)

### ISSUE THREAD

**Issue by mbombonato** [ad-on-is/adonis-autoswagger#3]
It should be **including** instead **inlcuding**

https://github.com/ad-on-is/adonis-autoswagger/blob/24877698a1427c3b0e237bb1f559b8d013fe31d0/src/autoswagger.ts#L554

Thanks for your work. I'm using here and it's waaaay more productive than using Swagger from scratch!

**Comment by ad-on-is** [comment]
Ah, thank you for the hint! I just published a fixed version (y)

I'm glad you like it 😉 The purpose is to automate as much as possible, while still offering some syntactic sugar for additional documentation, without bloating the files with comments.
