### ISSUE TITLE
In Post and Put Method Request Body Parameters are not show Swagger Ui 

### ISSUE THREAD

**Issue by MIQBALHASSAN** [ad-on-is/adonis-autoswagger#31]
I am using this package first time. I configured the package with given instructions. But In http Post Method Request Body Parameters are not show in Swagger Ui. Below I attached the screenshots. kindly guide me how to fix it.

<img width="1440" alt="Screenshot 2023-12-11 at 3 41 26 PM" src="https://github.com/ad-on-is/adonis-autoswagger/assets/90596612/114c0598-0af9-4328-a9f5-d06bd841c20a">

<img width="1393" alt="Screenshot 2023-12-11 at 3 46 30 PM" src="https://github.com/ad-on-is/adonis-autoswagger/assets/90596612/78b47cb2-1ae3-4119-a5fc-bc4af20f9903">

<img width="1420" alt="Screenshot 2023-12-11 at 3 39 10 PM" src="https://github.com/ad-on-is/adonis-autoswagger/assets/90596612/ae80e7f4-cf94-4d3c-9249-1549908f5824">

**Comment by ad-on-is** [comment]
Could you share your routes of company?

**Comment by MIQBALHASSAN** [comment]
this is company routes.
<img width="1435" alt="Screenshot 2023-12-11 at 4 03 08 PM" src="https://github.com/ad-on-is/adonis-autoswagger/assets/90596612/62a266c6-0065-46f8-9894-c7f4f94d546c">

**Comment by ad-on-is** [comment]
Do you have the needed comments for @requestBody() and @responseBody() in your controller, right above the create() method, and other methods, as documented in the readme?

**Comment by MIQBALHASSAN** [comment]
this company controller create method
<img width="1384" alt="Screenshot 2023-12-11 at 4 13 07 PM" src="https://github.com/ad-on-is/adonis-autoswagger/assets/90596612/3b0fff43-c53a-4e3c-bcf9-f243230f5bdf">

**Comment by MIQBALHASSAN** [comment]
<img width="1392" alt="Screenshot 2023-12-11 at 4 18 01 PM" src="https://github.com/ad-on-is/adonis-autoswagger/assets/90596612/cb8fa28a-5731-4d9c-aa8f-672be726bd25">

**Comment by ad-on-is** [comment]
Sorry to be rude, but have you read the Readme at all? 

Please read the instructions, they have everything you need, including practical examples, and how/where to place the comments properly.

**Comment by MIQBALHASSAN** [comment]
If my problem has been solved from readme file instructions. why I am Creating the issue and request to you how to solve the issue. I am confused how to use these instructions.

**Comment by MIQBALHASSAN** [comment]
I copied and pasted your example code but it did not work. kindly guide me on how to use it.

<img width="1427" alt="Screenshot 2023-12-11 at 4 55 39 PM" src="https://github.com/ad-on-is/adonis-autoswagger/assets/90596612/3147588d-9884-473b-b5c4-8b50e7e8a27f">

**Comment by ad-on-is** [comment]
Your first issue clearly lacked the requirements provided in the docs. 

Now that they look better, what issue do you have now? What's the output? I suppose you have no pagination set up, etc so you should remove the line paramuse(sortable, filterable)

Also, you can safely use your BaseController, there's no issue with that.
