### ISSUE TITLE
Feature Request - Change Default Controllers Location

### ISSUE THREAD

**Issue by HasanAshab** [ad-on-is/adonis-autoswagger#36]
I would like to have the ability to specify a custom location for my controller files. Currently, adonis-autoswagger scans the `app/Controllers/Http` directory by default, which may not always align with my preferred project structure.
that's also applicable to other components (interfaces, models...)

Proposed Solution:
To address this issue, I propose introducing a configuration option in adonis-autoswagger that allows users to specify a custom directory for their controllers. This option should be set in the adonis-autoswagger configuration file. Additionally, if no custom location is specified, adonis-autoswagger should fall back to checking the `adonisrc.json` file for a `controllers` property.

Example Configuration:
```typescript
module.exports = {
 // Other configurations...
 controllersPath: 'path/to/my/controllers',
}
```
Or in `adonisrc.json`:

With this configuration, adonis-autoswagger should scan the specified directory for controller files and generate Swagger documentation accordingly.

Benefits:
This feature would allow developers to organize their project structure according to their preferences, without having to modify the source code of adonis-autoswagger. It would also make it easier to integrate adonis-autoswagger into existing projects with non-standard controller locations.

Please let me know if you need any further information or clarification. I look forward to hearing from you soon.

Best regards,
Hasan Ashab

**Comment by HasanAshab** [comment]
very sorry, it was a misunderstanding

**Comment by ayush-cone** [comment]
Is this already possible in the library?

**Comment by aayush123** [comment]
Is this already possible in the library?

**Comment by ad-on-is** [comment]
Not yet... but PRs are welcome

**Comment by aayush123** [comment]
I unfortunately don't see anything about this in the docs. Can you link me to the section?

**Comment by ad-on-is** [comment]
https://github.com/ad-on-is/adonis-autoswagger?tab=readme-ov-file#practical-example

**Comment by ad-on-is** [comment]
It's done automatically if you modify the path in oackage.json
