### ISSUE TITLE
Adonisjs v6 support

### ISSUE THREAD

**Issue by tsiresymila1** [ad-on-is/adonis-autoswagger#39]
I think, it needs to alter directory name from Models to models, and Interfaces to interfaces and change or add more types

**Comment by Ziut3k-dev** [comment]
+1
  return AutoSwagger.default.docs(router.toJSON(), swagger)
    docs(routes: Record<string, RouteJSON[]>, options: options): Promise<any>;

**Comment by Ziut3k-dev** [comment]
@tsiresymila1 check #40

**Comment by tsiresymila1** [comment]
@Ziut3k-dev , Does it work with the new directory architecture?, does it load very well security middleware, models and interfaces ?

**Comment by Ziut3k-dev** [comment]
@tsiresymila1  not fully work, in few day i will work with this and add fully support for new adonis

**Comment by Ziut3k-dev** [comment]
if owner of repo dont release this i release this myself when i finish

**Comment by SwartZCoding** [comment]
> if owner of repo dont release this i release this myself when i finish

release it :)

**Comment by ad-on-is** [comment]
> if owner of repo dont release this i release this myself when i finish

Once you're done, just give me a heads up and I'll release it 👍

**Comment by ad-on-is** [comment]
I've started implementing v6 support with backwards compatibility to v5.
https://github.com/ad-on-is/adonis-autoswagger/tree/v6

Looking good so far

![image](https://github.com/ad-on-is/adonis-autoswagger/assets/9553253/639d0e1d-bcc5-4a83-b896-17f61704a17b)

The only issue I have right now is that I don't get any info about the middleware used in a specific route.
https://github.com/adonisjs/core/discussions/4403

**Comment by Ziut3k-dev** [comment]
Oh,nice,I didn't have time before
