### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by SwartZCoding** [ad-on-is/adonis-autoswagger#41]
Hello mate !

This morning trying to use your lib.

When i put on my routes.ts  AutoSwagger.docs & AutoSwagger.ui. I have AutoSwagger.docs is not a function &  AutoSwagger.swagger is not a function

Reproduce steps : 
1. npm i adonis-autoswagger
2. follow docs to add routes in routes.ts
3. config swagger.ts
4. try

**Comment by SwartZCoding** [comment]
> Hey... I assume you're on v6... I forgot to update the readme accordingly.
> 
> It should be `AutoSwaggger.default.docs()` and `AutoSwagger.default.ui()`

sure, now i have this : https://gyazo.com/af3a3eea99addf50d2c35dfbb5916a1b

**Comment by SwartZCoding** [comment]
And when i go on /docs page i have this error ERROR (13020): v6handler.reference.split is not a function and this : 

https://gyazo.com/0bc519ffd5117965d756495c7fb89de2

**Comment by ad-on-is** [comment]
> > Hey... I assume you're on v6... I forgot to update the readme accordingly.
> > It should be `AutoSwaggger.default.docs()` and `AutoSwagger.default.ui()`
> 
> sure, now i have this : https://gyazo.com/af3a3eea99addf50d2c35dfbb5916a1b on the swagger constructor args of ui & docs functions

Can you add a snakeCase: true to the swagger config. This should solve linting problem.

**Comment by SwartZCoding** [comment]
> > > Hey... I assume you're on v6... I forgot to update the readme accordingly.
> > > It should be `AutoSwaggger.default.docs()` and `AutoSwagger.default.ui()`
> > 
> > 
> > sure, now i have this : https://gyazo.com/af3a3eea99addf50d2c35dfbb5916a1b on the swagger constructor args of ui & docs functions
> 
> Can you add a snakeCase: true to the swagger config. This should solve linting problem.

Good for linting issue. But i always have the v6handler.reference.split is not a function when i go to /docs

**Comment by ad-on-is** [comment]
would you mind posting your `router.toJSON()`?

**Comment by SwartZCoding** [comment]
> would you mind posting your `router.toJSON()`?

https://hastebin.skyra.pw/wofixatube.yaml

**Comment by ad-on-is** [comment]
> > would you mind posting your `router.toJSON()`?
> 
> https://hastebin.skyra.pw/wofixatube.yaml

Strange, I have a similar route, where the handler is either an object or an async function, and it works.

What version of AutoSwagger are you on? and could you also post your routes.ts and config/swagger.ts

**Comment by SwartZCoding** [comment]
> > > would you mind posting your `router.toJSON()`?
> > 
> > 
> > https://hastebin.skyra.pw/wofixatube.yaml
> 
> Strange, I have a similar route, where the handler is either an object or an async function, and it works.
> 
> What version of AutoSwagger are you on? and could you also post your routes.ts and config/swagger.ts

2.2.0

My config swagger : 

`import path from 'node:path'
import url from 'node:url'

export default {
  path: path.dirname(url.fileURLToPath(import.meta.url)) + '/../', // for AdonisJS v6
  title: 'GemsRoll',
  version: '1.0.0',
  tagIndex: 2,
  snakeCase: true,
  ignore: ['/swagger', '/docs'],
  preferredPutPatch: 'PATCH', // if PUT/PATCH are provided for the same route, prefer PUT
  common: {
    parameters: {}, // OpenAPI conform parameters that are commonly used
    headers: {}, // OpenAPI conform headers that are commonly used
  },
  persistAuthorization: true, // persist authorization between reloads on the swagger page
}
`

routes.ts: 

`import router from '@adonisjs/core/services/router'
import '#routes/auth'
import '#routes/health'
import '#routes/folder'
import AutoSwagger from 'adonis-autoswagger'
import swagger from '#config/swagger'

router.get('/swagger', async () => {
  return AutoSwagger.default.docs(router.toJSON(), swagger)
})

// Renders Swagger-UI and passes YAML-output of /swagger
router.get('/docs', async () => {
  console.log(router.toJSON())
  return AutoSwagger.default.ui('/swagger', swagger)
})
`

**Comment by SwartZCoding** [comment]
I'm at work currently. So i try your future things later.

**Comment by ad-on-is** [comment]
```
import '#routes/auth'
import '#routes/health'
import '#routes/folder'
```
I see, you have your routes in separate files. I couldn't find anything in the official AdonisJS docs, hence I never tested it like that.

What did you do to make this work in adonisjs?

**Comment by SwartZCoding** [comment]
> ```
> import '#routes/auth'
> import '#routes/health'
> import '#routes/folder'
> ```
> 
> I see, you have your routes in separate files. I couldn't find anything in the official AdonisJS docs, hence I never tested it like that.
> 
> What did you do to make this work in adonisjs?

Nothing, just import files on routes.ts and it's work :) And i just need to import router and create new routes on this file

**Comment by ad-on-is** [comment]
Nevermind,

I added `"#routes/*": ["./routes/*.js"]`to tsconfig.json and `"#routes/*": "./routes/*.js"` to package.json, created a file routes/test.ts with some routes and it works without errors.

**Comment by ad-on-is** [comment]
> I'm having the same "split not a function" problem, here's the repo, it's an open test: https://github.com/VincentGillot/adonisjs-user-auth

Thx...
`router.get("/", [UsersController, "all"]);` this notation seems to have issues. Will look into it.

**Comment by ad-on-is** [comment]
Alright... the following notation cannot work.

```ts
const TestController = () => import("#controllers/test_controller");
router.get("/best", [TestController, "index"]);
```

This is because AutoSwagger does not know which file the controller/action originates from and hence cannot parse the comments. 
Use magic-strings instead, as it's also lazy loaded.

```ts
router.get("/best", "test_controller.index");
```

**Comment by ad-on-is** [comment]
Scratch what I said previously... I just implemented this notation, but it MUST be used with caution.

```ts
const FooController = () => import("#controllers/foo_controller");
router.get("/foo", [FooController, "index"]);
```

Since AutoSwagger does not know which file the controller/action originates from, the controller name MUST match the filename.
✅ FooController -> `controllers/foo_controller`
❌ FooController -> `controllers/bar_controller`
❌ FooController -> `controllers/foo`
❌ FooController -> `controllers/bar`

**Comment by SwartZCoding** [comment]
> Scratch what I said previously... I just implemented this notation, but it MUST be used with caution.
> 
> ```ts
> const FooController = () => import("#controllers/foo_controller");
> router.get("/foo", [FooController, "index"]);
> ```
> 
> Since AutoSwagger does not know which file the controller/action originates from, the controller name MUST match the filename. ✅ FooController -> `controllers/foo_controller` ❌ FooController -> `controllers/bar_controller` ❌ FooController -> `controllers/foo` ❌ FooController -> `controllers/bar`

Ok so 

const AuthController = () => import('#controllers/auth/auth_controller')
router
  .group(() => {
    router.post('/signin', [AuthController, 'login']).as('auth.signin')
    router.post('/signup', [AuthController, 'register']).as('auth.signup')
    router.get('/me', [AuthController, 'me']).as('auth.me').middleware(middleware.auth())
    router.post('/verify/:token', [VerifyEmailsController, 'verify']).as('verify.email.verify')
    router.post('/password/send', [UserPasswordResetsController, 'send']).as('password.send')
    router.post('/password/store', [UserPasswordResetsController, 'store']).as('password.store')
    router
      .post('/logout', [AuthController, 'logout'])
      .as('auth.logout')
      .middleware(middleware.auth())
  })
  .prefix('auth')
  
  don't work ? I have this error :  no such file or directory, open  \api\app\controllers\auth_controller.ts'. AutoSwagger can't go on /api/app/controllers/AUTH/auth_controller ?

**Comment by SwartZCoding** [comment]
Is not good because if app go bigger. Have all controllers in the same folders is not good

**Comment by ad-on-is** [comment]
> Is not good because if app go bigger. Have all controllers in the same folders is not good

As I already described, AutoSwagger does not know where the controller comes from. I'm happy for any suggestions on how to solve that problem.

**Comment by ad-on-is** [comment]
Alright... I think I got it working reliably now.
https://github.com/adonisjs/core/blob/develop/src/cli_formatters/routes_list.ts#L384 was again a huge help.

I added `parse-imports` to the package. Now it resolves correctly.

Have fun!

**Comment by ad-on-is** [comment]
If you still have issues, feel free to reopen.
