### ISSUE TITLE
docs_generate in AdonisJS ^6.2.2

### ISSUE THREAD

**Issue by brunojoao** [ad-on-is/adonis-autoswagger#44]
First, thx for this package

```

import { BaseCommand } from '@adonisjs/core/build/standalone'
import AutoSwagger from 'adonis-autoswagger'
import swagger from '../config/swagger'
export default class DocsGenerate extends BaseCommand {
  public static commandName = 'docs:generate'

  public static description = ""

  public static settings = {
    loadApp: true,

    stayAlive: false,
  }
  public async run() {
    const Router = await this.application.container.use('Adonis/Core/Route')
    Router.commit()
    await AutoSwagger.writeFile(await Router.toJSON(), swagger)
  }
}
```

![image](https://github.com/ad-on-is/adonis-autoswagger/assets/16447379/cb4380de-7845-4a6b-8358-82d8dd6cfcf2)
-------------------------
I tried to refactor this example to take the Route and transform it into toJson, but apparently this.application.container.use is deprecated, so I tried changing it to this.app but it doesn't have the .use, does anyone know what the call is like now in the new version ?

**Comment by brunojoao** [comment]
i changed 2 lines to:
```
import { BaseCommand } from '@adonisjs/core/ace'
import swagger from '#config/swagger'
```
![image](https://github.com/ad-on-is/adonis-autoswagger/assets/16447379/3d31f42e-b721-45ee-8f80-5a99f21f41da)
--
I couldn't find in the Adonis documentation how to get the json from the route =/

**Comment by ad-on-is** [comment]
Hey, thx... 

I just updated the README for the v6 docs generation, and there's a new `DocsGeneratev6.ts.example`
