### ISSUE TITLE
schema name mismatch with model name in v6 - suggest to add option for PascalCase

### ISSUE THREAD

**Issue by zecar** [ad-on-is/adonis-autoswagger#45]
Adonis models file names are now snake_case

for example: `models/reward_type.ts` will result in yaml schema name of `reward_type` 

The issue is that when this model is referenced inside another model, it's with the name of its class that is pascal case RewardType

```
rewardType:
    $ref: "#/components/schemas/RewardType"
```

**Comment by zecar** [comment]
i know we can add reward_type as the model. the issue if that rewardType is a relationship inside another model Reward.rewardType. So this relationship is not added to the reward model inside swagger

**Comment by ad-on-is** [comment]
Does `snakeCase: false` in config/swagger.ts solve the issue?

**Comment by zecar** [comment]
snakeCase seems to only affect property name inside model

![image](https://github.com/ad-on-is/adonis-autoswagger/assets/8117818/a33ce16d-fea8-4e43-8a35-84d72dc444e9)

from rewardType to reward_type

but inside yaml, the $ref is still PascalCase

![image](https://github.com/ad-on-is/adonis-autoswagger/assets/8117818/874d0334-77ff-4297-b175-ada51bd62e48)

**Comment by ad-on-is** [comment]
It should be fixed now in 2.8.0

**Comment by zecar** [comment]
yes, I confirm it's working
