### ISSUE TITLE
getting fullPath after summery

### ISSUE THREAD

**Issue by zecar** [ad-on-is/adonis-autoswagger#47]
![image](https://github.com/ad-on-is/adonis-autoswagger/assets/8117818/97bb8b04-e71a-49b4-9699-0dc0eaaf4d97)

in config/swagger.ts
![image](https://github.com/ad-on-is/adonis-autoswagger/assets/8117818/5999bf31-e76d-4d29-a390-63f3b1e1b26c)

**Comment by ad-on-is** [comment]
This is by design

**Comment by zecar** [comment]
oh, the screenshot on Readme showed only the path starting from App. Anyway we can have this as an option? The full path might get very long and is not really useful in my opinion

**Comment by zecar** [comment]
i opened a PR. full disclosure, i wrote that code in the github web ide without running the project. But i believe it does the trick
