### ISSUE TITLE
route.middleware.forEach is not a function [v6]

### ISSUE THREAD

**Issue by maukoese** [ad-on-is/adonis-autoswagger#49]
I'm getting this error when I try to generate the docs for v6. All of my routes have middleware (guest or auth), but /swagger and ```node ace docs:generate``` both give me the error.

See the screenshot for reference:

<img width="1200" alt="Screenshot 2024-02-18 at 16 07 39" src="https://github.com/ad-on-is/adonis-autoswagger/assets/14233942/7970d115-65ab-4294-8d34-c266c9ba751b">

The middleware on the route is not an array, so the .forEach fails.

**Comment by ad-on-is** [comment]
does the UI/swagger endpoint itself work? /docs /swagger? Or does that give an error too?

**Comment by maukoese** [comment]
Never mind. Just realized I was using an older version of the package. Updated and everything works okay.

**Comment by maukoese** [comment]
Thank you so much for your quick response.

**Comment by ad-on-is** [comment]
Glad I could help.
