### ISSUE TITLE
Feature Request: responseBody - @usePagination()

### ISSUE THREAD

**Issue by zecar** [ad-on-is/adonis-autoswagger#50]
It would be very helpful to have a @usePagination annotation for responseBody that conforms to how lucid returns paginated results

```
{
  "meta": {
    "total": 50,
    "perPage": 5,
    "currentPage": 1,
    "lastPage": 10,
    "firstPage": 1,
    "firstPageUrl": "/?page=1",
    "lastPageUrl": "/?page=10",
    "nextPageUrl": "/?page=2",
    "previousPageUrl": null
  },
  "data": []
}
```

**Comment by ad-on-is** [comment]
I myself am really not a fan of such Implementations and I think they're better off being handled in header parameters instead, since it makes it inconsistent with the rest of the API.

Sometimes it returns `[]` and other times it returns `{data' []}` and consumers of the API rely on thoroughly reading the specs.

But sure, will do when I have time for it. Also PRs are more than welcome.

**Comment by maukoese** [comment]
@ad-on-is sorry to reopen this, but did you ever have a look at this? For large APIs data is almost always paginated, and the metadata retured by lucid has some vital info such as total and number of pages that the frontend teams like. so I suppose providing a ```<Paginated<Model>>``` helper would really help. 

Something like this, which in the docs returns the structure as above.


```typescript
/**
   * @index
   * @summary List all users
   * @description List all users with pagination and filters
   *
   * @paramQuery page
   * @paramQuery per
   *
   * @responseBody 200 - <Paginated<User>>.with(relations)
   * @paramUse(sortable, filterable)
   * @responseHeader 200 - @use(paginated)
   */
  async index({ response, request }: HttpContext) {}
```

If you point me in the right direction I could assist with this.

**Comment by ad-on-is** [comment]
you could create a new Interface with the metainfo, and then do the following:

```
@responseBody 200 - {"data": "<User[]>", "meta": "<MetaInterface>"}
```

**Comment by maukoese** [comment]
It's not picking correctly
<img width="1477" alt="Screenshot 2024-04-06 at 19 38 47" src="https://github.com/ad-on-is/adonis-autoswagger/assets/14233942/1f4c6d4e-5f55-4473-b8a4-cc19e32e33c6">

This is how I have configured it

![Uploading pagination.png…]()

**Comment by maukoese** [comment]
The interface is defined and shows up

<img width="538" alt="Screenshot 2024-04-06 at 19 50 41" src="https://github.com/ad-on-is/adonis-autoswagger/assets/14233942/abeeeedc-01e9-463a-a427-bacb314455e8">

**Comment by ad-on-is** [comment]
Could you just try "<Account[]>" without the .with() notation

**Comment by maukoese** [comment]
Still doesn't work.

<img width="1473" alt="Screenshot 2024-04-06 at 20 07 27" src="https://github.com/ad-on-is/adonis-autoswagger/assets/14233942/4edf4234-a5ef-4e77-94b2-51ef6cd42e2b">

**Comment by ad-on-is** [comment]
ok... looks like a bug then... will have a look into it

**Comment by maukoese** [comment]
Alright, thanks.

**Comment by ad-on-is** [comment]
This should be fixed in 3.8.0 now.. Also, there's a `<Model[]>.paginate()` helper to generate `{data:[], meta:{}}` automatically.

**Comment by maukoese** [comment]
You are amazing, thank you! Let me test it out.

**Comment by maukoese** [comment]
This one works, thank you!

<img width="1454" alt="Screenshot 2024-04-08 at 14 45 40" src="https://github.com/ad-on-is/adonis-autoswagger/assets/14233942/783dcba6-c508-496e-acb4-e1d15c043ceb">

The .paginate() helper isn't working for me though. It just returns the model. 

<img width="1469" alt="Screenshot 2024-04-08 at 14 47 50" src="https://github.com/ad-on-is/adonis-autoswagger/assets/14233942/a8af2838-62b5-4689-a535-986730384776">

**Comment by ad-on-is** [comment]
Would you mind sharing your code on how you integrated the .paginate() in your controller?

**Comment by ad-on-is** [comment]
> The .paginate() helper

it's **.paginated()** (with a "d" at the end)

**Comment by maukoese** [comment]
.paginated() works like a charm! Thank you so much.

**Comment by ad-on-is** [comment]
I'm glad to hear that 👍️

**Comment by maukoese** [comment]
Add it in the docs maybe?

**Comment by ad-on-is** [comment]
It already is in the readme

**Comment by zecar** [comment]
If you guys are interested, I've added a Response macro to conform the returned results from Lucid to headers like this:

![image](https://github.com/ad-on-is/adonis-autoswagger/assets/8117818/85d2065e-f642-48df-864e-b65123334cea)

Usage:
![image](https://github.com/ad-on-is/adonis-autoswagger/assets/8117818/55a9c24c-a577-4e85-81f0-9c27e55fd36d)

Swagger result:
![image](https://github.com/ad-on-is/adonis-autoswagger/assets/8117818/b049640d-9db9-4297-9bfb-a29cb5b78232)

**Comment by ad-on-is** [comment]
@zecar I think it'd be better to post the code properly, so everyone can just copy&paste it.

```ts
// your code here...
```

**Comment by zecar** [comment]
`import type { ApplicationService } from '@adonisjs/core/types'
import { Response } from '@adonisjs/core/http'
import { ModelPaginatorContract } from '@adonisjs/lucid/types/model'

declare module '@adonisjs/core/http' {
  export interface Response {
    withPagination(data: ModelPaginatorContract<any>): any[]
  }
}
export default class ResponsePaginationProvider {
  constructor(protected app: ApplicationService) {}
  async boot() {
    Response.macro(
      'withPagination',
      function (this: Response, data: ModelPaginatorContract<any>): any[] {
        const { currentPage, lastPage, perPage } = data.getMeta()
        this.safeHeader('X-Total-Pages', lastPage)
        this.safeHeader('X-Current-Page', currentPage)
        this.safeHeader('X-Per-Page', perPage)
        return data.all()
      }
    )
  }
}
`
