### ISSUE TITLE
Bug: Problem when using the "Date" type

### ISSUE THREAD

**Issue by 0xNekr** [ad-on-is/adonis-autoswagger#59]
When a model uses the `Date` type and not `Datetime`, auto-swagger doesn't recognize this type and therefore doesn't propose the example value correctly (and the `// @example` doesn't work).

However, Date format support seems to have been added here: https://github.com/ad-on-is/adonis-autoswagger/pull/38

I therefore propose simply adding the `Date` format to lists of standard type. 

I've tested this and it seems to work on my side, so I'm going to link a pull request to this issue. 

Don't hesitate to ask if I've left anything out.

**Comment by 0xNekr** [comment]
Issue related to https://github.com/ad-on-is/adonis-autoswagger/pull/58

**Comment by ad-on-is** [comment]
Hey.. Thx for this one.. It's merged and published to 2.16
