### ISSUE TITLE
Feat: Cofigurable Interface Location

### ISSUE THREAD

**Issue by HasanAshab** [ad-on-is/adonis-autoswagger#65]
It would be nice if we can configure **interfaces** directory. Currently it scans **app/interfaces** dir for interfaces.

A new config property **interfacesPath** can be added

May I make a PR for this?

**Comment by ad-on-is** [comment]
Done in 3.4.0. Modify package.json as follows. This also works for models.

```json
//...
"imports": {
  // ...
  "#interfaces/*": "./app/custom/path/interfaces/*.js"
  // ...
}
//...

```

**Comment by HasanAshab** [comment]
That's great... :)
