### ISSUE TITLE
Scalar API Client Proxy Error

### ISSUE THREAD

**Issue by maukoese** [ad-on-is/adonis-autoswagger#69]
I love te new Scalar docs, they are very beautiful and well structured.

However, when I try to make any request to test out the API I get the above error.

<img width="1792" alt="Screenshot 2024-04-08 at 15 03 16" src="https://github.com/ad-on-is/adonis-autoswagger/assets/14233942/3a3c0ba0-d922-424d-9032-12980439fa80">

My config is as below:

```js
import path from 'node:path'
import url from 'node:url'

export default {
  path: path.dirname(url.fileURLToPath(import.meta.url)) + '/../',
  title: 'SBDC API',
  version: '1.0.0',
  tagIndex: 2,
  snakeCase: false,
  ignore: [
    '/swagger',
    '/docs',
    '/api/internal',
    '/admin',
    // '/partner',
    // '/login',
    // '/register',
    '/jobs',
    '/2fa',
    '/logout',
    '/password',
    '/inertia',
    '/ask',
    '/about',
    '/contact',
    '/auth/*',
    '/portfolio',
    '/our-partners',
    '/p/*',
    '/c/*',
  ],
  preferredPutPatch: 'PUT',
  common: {
    parameters: {
      page: 1,
      per: 10
    },
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/json',
    },
  },
  persistAuthorization: true,
  showFullPath: false,
}
```

and the routes

```js
router.get('swagger', async () => {
  return AutoSwagger.default.docs(router.toJSON(), swagger)
})

router.get('docs', async () => {
  // return AutoSwagger.default.ui('/swagger', swagger)
  return AutoSwagger.default.scalar('/swagger')
})
```

**Comment by ad-on-is** [comment]
I'm not 100% sure, but looks like scalar calls _api.scalar.com_ which then tries to connect to **localhost:333** (in my case) .. and this obviously wouldn't work, since their server does not know anything about localhost:3333.

I assume, this should work if your app is hosted publicly with an accessible URL like _https://myapp.googleapps.com_ or similar.

**Comment by ad-on-is** [comment]
Did it work on production?

**Comment by maukoese** [comment]
@ad-on-is Yes it does, thank you.

**Comment by EvandroVV93** [comment]
@maukoese 

`
import scalarCustomCss from '#config/scalar'

router.get('/docs', async () => {
  return `
  <!doctype html>
  <html>
    <head>
      <title>API</title>
      <meta charset="utf-8" />
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1" />
      <style>
      ${scalarCustomCss}
      </style>
    </head>
    <body>
      <script
        id="api-reference"
        data-url="/swagger"
      <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
    </body>
  </html>
`
})`

this works if still want to use scalar!
