### ISSUE TITLE
Feature request: manual tag

### ISSUE THREAD

**Issue by zecar** [ad-on-is/adonis-autoswagger#72]
I have common endpoints like `/entity`, `/entity2` which get's correctly auto tagged under "ENTITY" or "ENTITY2"

the issues comes when I have admin routes for those entities like `/admin/entity`; `/admin/entity2` because both of them are under "ADMIN"
 
Can we have a decorator for @tag?

![image](https://github.com/ad-on-is/adonis-autoswagger/assets/8117818/d549ebe9-36fc-41c5-9fe4-bf37be18c851)

**Comment by ad-on-is** [comment]
Done in 3.10.0
