### ISSUE TITLE
Token header with other type not Bearer

### ISSUE THREAD

**Issue by Bruno-Alvim-Duarte** [ad-on-is/adonis-autoswagger#74]
We can't change the type of the token header, it is defined Bearer and can't change the securityDefinitions to apiKey for example

**Comment by Bruno-Alvim-Duarte** [comment]
Right, i was in the 3.11 version haven't seen that. Thank you

**Comment by ad-on-is** [comment]
And I pushed the feature in 3.13 after you submitted the issue... so there was nothing to see until then 😅

**Comment by Bruno-Alvim-Duarte** [comment]
Oh, right so thanks for the correction in the new version :smile:
