### ISSUE TITLE
Production bug: trying to load different file

### ISSUE THREAD

**Issue by zecar** [ad-on-is/adonis-autoswagger#75]
In production build, the /swagger route tries to load
`ep2-api/build/config/../swagger.yaml` -> .yaml, but the generated file is .yml

I believe it's because of this line: https://github.com/ad-on-is/adonis-autoswagger/blob/1ac53bfab9c080ff5fc48504bdb3f97d02c9db1a/src/autoswagger.ts#L154

**Comment by ad-on-is** [comment]
Oh... thx.. fixed in 3.12.0
