### ISSUE TITLE
Question: How to Omit controller methods from the docs which doesn't exists

### ISSUE THREAD

**Issue by MrSharpp** [ad-on-is/adonis-autoswagger#77]
So basically i have created 4 controllers, with few methods in each. 
not all controllers implements all methods.

But when i try to look at up in docs, it shows all methods, and for one controller it doesnt even shows its name.

So is there any way so instead of auto generating it, i can just tag to the controller to which i want the docs to be generated?
like a decorator?

**Comment by ad-on-is** [comment]
you can use the ignore in the swagger config to ignore specific routes.

> for one controller it doesnt even shows its name.
just check the docs. If something doesn't work as documented, report back.

> So is there any way so instead of auto generating it
this is literally the whole purpose of this library 😂
