### ISSUE TITLE
Documentation description?

### ISSUE THREAD

**Issue by Bruno-Alvim-Duarte** [ad-on-is/adonis-autoswagger#78]
How can I define my doc description? At the swagger option (config/swagger.ts) doesn't have a description key

**Comment by ad-on-is** [comment]
Oopsy, daisy :-D

Fixed in 3.14.0, but also 3.16.0 adds an info-object to the config so you can pass all the fields that swagger supports: https://swagger.io/docs/specification/api-general-info/
