### ISSUE TITLE
Feature request: Only routes

### ISSUE THREAD

**Issue by Dolu89** [ad-on-is/adonis-autoswagger#81]
Like the `ignore` option, add a `only: string[]` option to only accept routes like 
```json
{
  only: ['/api/_']
}
```
I think it should be usable WITH `ignore` to only apply routes like /api and ignore /docs /swagger (default name provided by the doc)

**Comment by ad-on-is** [comment]
PRs are always welcome.

Also, I think the number of routes that should be shown outweights the ones that shouldn't. So this is mostly redundant, especially since the config is copy & paste, which has everything setup correctly.
