### ISSUE TITLE
Bug Report - empty swagger sections after usage of @tag

### ISSUE THREAD

**Issue by zecar** [ad-on-is/adonis-autoswagger#83]
If i have a route defined for "one-two" and for that controller action I set "@tag One Two", swagger will show a section for "ONE-TWO" that is empty

**Comment by ad-on-is** [comment]
please post your controller comments

**Comment by zecar** [comment]
`/admin/user` -> will produce ADMIN-USER

`@tag Admin User`-> it will produce ADMIN USER (without a dash) and will display /admin/user under this tag

then,. the first tag autocreated from route will be displayed without any content inside

**Comment by zecar** [comment]
`router.get('/z', [SlotslaunchController, 'test'])` -> this will create a section in swagger called "Z everything related to Z"

adding a different @tag like this
![image](https://github.com/ad-on-is/adonis-autoswagger/assets/8117818/4cc5fc00-39b6-48cd-a60b-08b464ed4235)
will create a section called "ZZ everything related to Z"

this will leave the previous section "Z" to be left empty

![image](https://github.com/ad-on-is/adonis-autoswagger/assets/8117818/3ac98ec6-2c91-43ad-bce9-62696b5be40e)
