### ISSUE TITLE
serializeAs: null not auto-detected

### ISSUE THREAD

**Issue by zecar** [ad-on-is/adonis-autoswagger#85]
![image](https://github.com/ad-on-is/adonis-autoswagger/assets/8117818/46105397-b866-4858-9681-b628315b4ad6)
![image](https://github.com/ad-on-is/adonis-autoswagger/assets/8117818/082f8c87-0df0-446b-a885-af13fce2ea17)

**Comment by ad-on-is** [comment]
Yeah...I can't take care of all AdonisJS model/serialize features.. just use the <Model>.without(url) notation.
