### ISSUE TITLE
Make camelCase fields possibility

### ISSUE THREAD

**Issue by yariksav** [ad-on-is/adonis-autoswagger#9]
Hi!
Thank you for your project!

But we have one notice, in module you did hardcode with snake_kase field in model and query params.
https://github.com/ad-on-is/adonis-autoswagger/blob/ba8b7636f9dca6e3816026286daa881352b51906/src/autoswagger.ts#L1118
Can you make this optionally, because we use always camelCase in our API?

Thank you!

**Comment by yariksav** [comment]
Yes, but I did this hack in "start" to disable it. 

```
BaseModel.namingStrategy.serializedName = (_, key: string) => {
  return key
}
BaseModel.namingStrategy.columnName = (_, key: string) => {
  return key
}
```

Maybe now creators of Adonis did the possibility to switch, I didn't investigate.
But in our requirements API must be in camelCase.
I don't understand why creators force you to do snak_case API... and no other chance :)

THanks for answer

**Comment by yariksav** [comment]
As I found they did NamingStrategies, and now made only SnakeCase, but maybe in the future, they will provide camelCase and others...

https://github.com/adonisjs/lucid/tree/develop/src/Orm/NamingStrategies

**Comment by yariksav** [comment]
Wow! Thank you very much! 
But i have one notice, you did
```
  if (this.options.snakeCase) {
        field = snakeCase(field);
  }
 ```
 Perhaps it will break the logic who used your module before, because they didn't have option snakeCase=true, and result will be in camelCase by default.
 I would make snake_case by default somehow, for example
 ```
   if (this.options.snakeCase !== false) {
        field = snakeCase(field);
  }
  ```
   ```
   if (!this.options.camelCase) {
        field = snakeCase(field);
  }
  ```

**Comment by yariksav** [comment]
Good! Thank you very much again, and have a wonderful day! :)

**Comment by ad-on-is** [comment]
Thx... you too!
