### ISSUE TITLE
required field in schema

### ISSUE THREAD

**Issue by pdipax** [ad-on-is/adonis-autoswagger#90]
Hi,
if I write @props({"required": true}) in the model
this work only for the swagger standard UI but only in properties of schema field.

The schema OpenAPI is not correct because the object it should be written like this

    App:
      type: "object"
      required:
        - description
        - code
        - blablabla

while it is currently populated in the schema field properties. If it were possible, a new @required decorator should be added which, if indicated in the model column, should correctly populate the information in the yaml model

**Comment by ad-on-is** [comment]
this is meant just for metadata like minlemgth, etc... maybe I should rename it to meta
