### ISSUE TITLE
Model and interfaces not found on windows environment adonisjs 6

### ISSUE THREAD

**Issue by sanchric-forvia** [ad-on-is/adonis-autoswagger#97]
After install and configure the package, model was not loaded using custom path on package.json

for example
 
![image](https://github.com/ad-on-is/adonis-autoswagger/assets/168569160/2229a20d-4852-4d0f-b3fa-9cd3b9c0cea7)

After debug on getModels and getInterfaces there is a condition that replace the path in case custom path 

![image](https://github.com/ad-on-is/adonis-autoswagger/assets/168569160/6294d00e-7a54-4169-8bca-76d905365442)

but as windows the path split character is '\' not found a match to replace, my quick fix was add another line to replace looking for '\'

![image](https://github.com/ad-on-is/adonis-autoswagger/assets/168569160/075f529b-9ac5-4d60-bb4b-791efffe0ccd)

I hope this can be fix on next version

Note: Could be great if the custom paths not depends of package.json and set better on config as an array of path to check

**Comment by ad-on-is** [comment]
Oh thx for that... Will add a fix
The custom paths MUST depend on the package.json, since it's how adonisJS handles them too.

**Comment by ad-on-is** [comment]
Should be fixed in the latedt version

**Comment by sanchric-forvia** [comment]
Excellent service 5 starts :D, this is great thanks !!!!!
