### ISSUE TITLE
 Only URLs with a scheme in: file, data,  and node are supported by the default ESM loader.

### ISSUE THREAD

**Issue by FaiezWaseem** [ad-on-is/adonis-autoswagger#98]
Hi upon running `node ace docs:generate` it worked before , but now after adding vinejs and validations now on running this command suddenly i am getting this error 

[ error ] Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, abs
olute paths must be valid file:// URLs. Received protocol 'c:'                                                               at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:239:11)
          at defaultLoad (node:internal/modules/esm/load:130:3)
          at nextLoad (node:internal/modules/esm/hooks:750:28)
          at C:\Development\web\node\adonijs-nextjs\server\node_modules\ts-node\src\esm.ts:255:45
          at async addShortCircuitFlag (C:\Development\web\node\adonijs-nextjs\server\node_modules\ts-node\src\esm.
ts:409:15)                                                                                                                   at async nextLoad (node:internal/modules/esm/hooks:750:22)
          at async Hooks.load (node:internal/modules/esm/hooks:383:20)
          at async handleMessage (node:internal/modules/esm/worker:199:18)

**Comment by mGGk-fr** [comment]
I have the same after updating to latest AdonisJS

**Comment by ad-on-is** [comment]
Oh boy... I hate the JS stack 🙄 will have a look into it

**Comment by ad-on-is** [comment]
I just deployed a possible fix in 3.47.0. Can you guys test it with that version? Otherwise I might need some help here from the windows folks.

**Comment by FaiezWaseem** [comment]
@ad-on-is Ok  i will test it  now

**Comment by FaiezWaseem** [comment]
well So I tried the update .
When i run the command node ace docs:generate , it runs successfully but when visits the docs 
![error1](https://github.com/ad-on-is/adonis-autoswagger/assets/78906502/b8b185aa-e92c-4912-92f8-6bd3ad5b3510)

But when i debug a little more  i added this route

```
router.get('/swagger.json', async () => {
  const json = fs.readFile('swagger.json','utf8')
  return AutoSwagger.default.writeFile(json, swagger);
});
```
now its giving this error

![out+error](https://github.com/ad-on-is/adonis-autoswagger/assets/78906502/433340d6-1e39-4e0c-87fd-40f4b4576f3d)

but comment.ts exists , it have already created the swagger.json


![swagger](https://github.com/ad-on-is/adonis-autoswagger/assets/78906502/46cd912a-ba21-4353-9dca-343221bc3adc)


here is the [github repo](https://github.com/FaiezWaseem/adonijs-nextjs) of my project 

Node v21.7.3
AdonisJs  ^6.9.0
adonis-autoswagger ^3.47.0

**Comment by ad-on-is** [comment]
Thx for the reproduction... This is an issue with `node ace serve --hmr` 
Using `node ace serve --watch`  however, works as expected.

**Comment by ad-on-is** [comment]
@FaiezWaseem 

Also... your config is wrong here.

```ts
router.get("/swagger", async () => {
  return router.toJSON()
});
router.get("/docs", async () => {
  return AutoSwagger.default.ui("/swagger", swagger);
});
```

should be


```ts
router.get("/swagger", async () => {
  return AutoSwagger.default.docs(swagger);
});
router.get("/docs", async () => {
  return AutoSwagger.default.ui("/swagger", swagger);
});
```

**Comment by ad-on-is** [comment]
Close in favor of https://github.com/ad-on-is/adonis-autoswagger/issues/102

**Comment by FaiezWaseem** [comment]
Yup fixed Working now
