### ISSUE TITLE
Use swagger offline

### ISSUE THREAD

**Issue by sanchric-forvia** [ad-on-is/adonis-autoswagger#99]
Could be possible had swagger files locally on the project, if app is on intranet and is not possible download from CDN nothing can be done

![image](https://github.com/ad-on-is/adonis-autoswagger/assets/168569160/3d77aceb-a48c-4e79-96ac-67a566413357)

Many companies use the tools on intranet and is not possible download content from CDN

**Comment by ad-on-is** [comment]
you can do that in your adonisjs project yourself. just use the route to render the swagger ui yourself however you like and use the `/swagger` endpoint for the yaml.

**Comment by sanchric-forvia** [comment]
Yeah that works great

![image](https://github.com/ad-on-is/adonis-autoswagger/assets/168569160/f86e931d-f525-463f-ab1d-0c6b4d8cae50)

But /docs depends on download


![image](https://github.com/ad-on-is/adonis-autoswagger/assets/168569160/ec327349-16a3-4a0c-b8f5-7334e0385538)


so on intranet the swagger ui is not displayed

**Comment by sanchric-forvia** [comment]
Ok, I think i get your point, I will try to do it

**Comment by ad-on-is** [comment]
Instead of using Autoswagger.ui(), just render your own template
